# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
    nginx:
        # используем последний стабильный образ nginx
        image: nginx:latest
        # маршрутизируем порты
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - php
    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: 
            context: ./images/php
            dockerfile: Dockerfile
        # этот образ будет общаться с mysql
        links:
            - mysql
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
    mysql:
        image: mysql:5.7.22
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        # задаем пароль для root пользователя
        environment:
            MYSQL_USER: homestead 
            MYSQL_ROOT_PASSWORD: root
    phpmyadmin:
        # phpmyadmin
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin 
        environment: 
          PMA_ARBITRARY: 1 
          MYSQL_USER: homestead 
          MYSQL_ROOT_PASSWORD: root 
        volumes:
          - /sessions
          - ~/images/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        ports: 
            - "8090:80" 
        links: 
        # for mysql
            - php 
            - mysql
        depends_on:
            - nginx        

